CREATE TABLE [dbo].[test_user] (
  [id] varchar(36) COLLATE Chinese_PRC_CS_AS_WS  NOT NULL,
  [name] varchar(255) COLLATE Chinese_PRC_CS_AS_WS  NULL,
  CONSTRAINT [PK__user__3213E83F28AFA377] PRIMARY KEY CLUSTERED ([id])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[test_user] SET (LOCK_ESCALATION = TABLE)
